# Generated by Django 3.2.2 on 2021-10-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('categoria', models.CharField(default='', max_length=5, verbose_name='categorias')),
            ],
            options={
                'db_table': 'e_shop_categoria',
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('talle', models.CharField(blank=True, default='', max_length=5, verbose_name='talles')),
            ],
            options={
                'db_table': 'e_shop_talle',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('art_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo_art')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('color', models.CharField(default='', max_length=20, verbose_name='color')),
                ('precio', models.FloatField(default=0.0, max_length=5, verbose_name='precio')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='stock qty')),
                ('picture', models.ImageField(default='', upload_to=None, verbose_name='picture')),
                ('categoria_id', models.ForeignKey(blank=True, max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.categoria', verbose_name='categoria_id')),
                ('talle_id', models.ForeignKey(blank=True, max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.talle', verbose_name='talle_id')),
            ],
            options={
                'db_table': 'e_shop_articulo',
            },
        ),
    ]
