# Generated by Django 3.2.2 on 2021-10-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categ', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('categorias', models.CharField(default='', max_length=5, verbose_name='categorias')),
            ],
            options={
                'db_table': 'e_shop_categorias',
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id_talle', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('talle', models.CharField(default='', max_length=5, verbose_name='talles')),
            ],
            options={
                'db_table': 'e_shop_talle',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('art_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='art ids')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('color', models.CharField(default='', max_length=20, verbose_name='color')),
                ('precio', models.FloatField(default=0.0, max_length=5, verbose_name='precio')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='stock qty')),
                ('picture', models.ImageField(default='', upload_to=None, verbose_name='picture')),
                ('categoria', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.categoria', verbose_name='categoria')),
                ('talle', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.talle', verbose_name='talle')),
            ],
            options={
                'db_table': 'e_shop_articulos',
            },
        ),
    ]
