# Generated by Django 3.2.2 on 2022-05-03 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('art_id', models.PositiveIntegerField(unique=True, verbose_name='codigo_art')),
                ('nombre', models.CharField(default='', max_length=80, verbose_name='nombre')),
                ('talle_xs', models.PositiveIntegerField(default=0, verbose_name='xs')),
                ('talle_s', models.PositiveIntegerField(default=0, verbose_name='s')),
                ('talle_m', models.PositiveIntegerField(default=0, verbose_name='m')),
                ('talle_l', models.PositiveIntegerField(default=0, verbose_name='l')),
                ('talle_xl', models.PositiveIntegerField(default=0, verbose_name='xl')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('picture', models.ImageField(null=True, upload_to='shop/images')),
                ('picture_1', models.ImageField(null=True, upload_to='shop/images')),
                ('picture_2', models.ImageField(null=True, upload_to='shop/images')),
                ('picture_3', models.ImageField(null=True, upload_to='shop/images')),
            ],
            options={
                'db_table': 'e_shop_articulo',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('categoria', models.CharField(default='', max_length=20, unique=True, verbose_name='categoria')),
                ('picture_cat', models.ImageField(null=True, upload_to='shop/images')),
            ],
            options={
                'db_table': 'e_shop_categoria',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('color', models.CharField(default='', max_length=20, verbose_name='color')),
            ],
            options={
                'db_table': 'e_shop_color',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('cart', models.BooleanField(default=False, verbose_name='carts')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished qty')),
                ('buyed_qty', models.PositiveIntegerField(default=0, verbose_name='buyed qty')),
                ('art_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='e_shop.articulo', verbose_name='Articulo')),
                ('user_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'e_shop_wish_list',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('talle', models.CharField(default='', max_length=50, verbose_name='talle')),
                ('buyed_qty', models.PositiveIntegerField(default=0, verbose_name='buyed qty')),
                ('art_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='e_shop.articulo', verbose_name='Articulo')),
                ('user_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'e_shop_item',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria_id',
            field=models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='e_shop.categoria', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='color_id',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='e_shop.color', verbose_name='color_id'),
        ),
    ]
