# Generated by Django 3.2.2 on 2022-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_qty',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='talle',
            field=models.CharField(default='', max_length=5, verbose_name='talle'),
        ),
    ]
