# Generated by Django 3.2.2 on 2021-10-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articulo',
            table='e_shop_articulo',
        ),
    ]
