# Generated by Django 3.2.2 on 2022-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='stock_qty'),
        ),
    ]
