# Generated by Django 3.2.2 on 2022-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='picture',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='picture_1',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='picture_2',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='picture_3',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
    ]
