# Generated by Django 3.2.2 on 2022-03-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='cantidad',
        ),
    ]
