# Generated by Django 3.2.2 on 2021-10-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default='', max_length=20, verbose_name='categorias'),
        ),
    ]
