# Generated by Django 3.2.2 on 2022-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_auto_20220504_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='talle',
        ),
        migrations.AddField(
            model_name='articulo',
            name='talle',
            field=models.CharField(default='', max_length=10, verbose_name='talle'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='wished qty'),
        ),
    ]
