# Generated by Django 3.2.2 on 2022-01-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_articulo_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='talle_id',
            field=models.ForeignKey(blank=True, max_length=5, on_delete=django.db.models.deletion.CASCADE, to='e_shop.talle', verbose_name='talle'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default='', max_length=20, verbose_name='categoria'),
        ),
    ]
