# Generated by Django 3.2.2 on 2021-10-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_alter_categoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria_id',
            field=models.ForeignKey(blank=True, max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talle_id',
            field=models.ForeignKey(blank=True, max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.talle', verbose_name='talle'),
        ),
    ]
