# Generated by Django 3.2.2 on 2022-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_remove_articulo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='codigo_art'),
        ),
    ]
