# Generated by Django 3.2.2 on 2022-01-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_auto_20220104_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_id',
            field=models.PositiveIntegerField(default=0, verbose_name='codigo_art'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
