# Generated by Django 3.2.2 on 2021-10-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_auto_20211021_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='talle_id',
            new_name='talle',
        ),
        migrations.RenameField(
            model_name='talle',
            old_name='talles',
            new_name='talle',
        ),
        migrations.AlterModelTable(
            name='talle',
            table='e_shop_talles',
        ),
    ]
