# Generated by Django 3.2.2 on 2022-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_auto_20220504_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='talle_elegido',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='talle_elegido'),
        ),
    ]
