# Generated by Django 3.2.2 on 2022-01-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_auto_20220104_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('color', models.CharField(default='', max_length=20, verbose_name='color')),
            ],
            options={
                'db_table': 'e_shop_color',
            },
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='talle_id',
        ),
        migrations.AddField(
            model_name='articulo',
            name='talle_l',
            field=models.PositiveIntegerField(default=0, max_length=5, verbose_name='l'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='talle_m',
            field=models.PositiveIntegerField(default=0, max_length=5, verbose_name='m'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='talle_s',
            field=models.PositiveIntegerField(default=0, max_length=5, verbose_name='s'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='talle_xl',
            field=models.PositiveIntegerField(default=0, max_length=5, verbose_name='xl'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='talle_xs',
            field=models.PositiveIntegerField(default=0, max_length=5, verbose_name='xs'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, max_length=5, verbose_name='stock_qty'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='color_id',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='e_shop.color', verbose_name='color_id'),
        ),
    ]
