# Generated by Django 3.2.2 on 2021-10-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0005_auto_20211021_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='talle',
            field=models.ForeignKey(blank=True, max_length=3, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.talle', verbose_name='talle'),
        ),
        migrations.AlterField(
            model_name='talle',
            name='talle',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='s', max_length=3),
        ),
    ]
