# Generated by Django 3.2.2 on 2022-01-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0005_auto_20220105_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='talle_l',
            field=models.PositiveIntegerField(default=0, verbose_name='l'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talle_m',
            field=models.PositiveIntegerField(default=0, verbose_name='m'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talle_s',
            field=models.PositiveIntegerField(default=0, verbose_name='s'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talle_xl',
            field=models.PositiveIntegerField(default=0, verbose_name='xl'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talle_xs',
            field=models.PositiveIntegerField(default=0, verbose_name='xs'),
        ),
    ]
