# Generated by Django 3.2.2 on 2022-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0005_auto_20220504_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wished_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='wished qty'),
        ),
    ]
