# Generated by Django 3.2.2 on 2022-01-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0006_auto_20220105_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='stock_qty'),
        ),
    ]
