# Generated by Django 3.2.2 on 2021-10-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0006_auto_20211021_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Jeans', 'JEANS'), ('Pant', 'PANTALONES'), ('Cam', 'CAMISAS'), ('Rem', 'REMERAS'), ('Swea', 'SWEATERS'), ('Camp', 'CAMPERAS'), ('Fald', 'FALDAS'), ('Vest', 'VESTIDOS'), ('Sac', 'SACOS'), ('Traj_baño', 'TRAJES DE BAÑO'), ('Calz', 'CALZADOS'), ('Acc', 'ACCESORIOS')], default='Jeans', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='talle',
            name='talle',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=3, unique=True),
        ),
    ]
