# Generated by Django 3.2.2 on 2022-01-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_alter_articulo_stock_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talle',
        ),
    ]
