# Generated by Django 3.2.2 on 2021-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_auto_20211021_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Jeans', 'JEANS'), ('Pantalones', 'PANTALONES'), ('Camisas', 'CAMISAS'), ('Remeras', 'REMERAS'), ('Sweaters', 'SWEATERS'), ('Camperas', 'CAMPERAS'), ('Faldas', 'FALDAS'), ('Vestidos', 'VESTIDOS'), ('Sacos', 'SACOS'), ('Trajes de baño', 'TRAJES DE BAÑO'), ('Calzados', 'CALZADOS'), ('Accesorios', 'ACCESORIOS')], default='Jeans', max_length=20, unique=True),
        ),
    ]
