# Generated by Django 3.2.2 on 2022-01-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0008_delete_talle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='stock_qty',
        ),
    ]
