# Generated by Django 3.2.2 on 2021-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0008_alter_categoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='picture',
            field=models.ImageField(default='', upload_to='picture', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Jeans', 'JEANS'), ('Pant', 'PANTALONES'), ('Cam', 'CAMISAS'), ('Rem', 'REMERAS'), ('Swea', 'SWEATERS'), ('Camp', 'CAMPERAS'), ('Fald', 'FALDAS'), ('Vest', 'VESTIDOS'), ('Sac', 'SACOS'), ('Traj_baño', 'TRAJES DE BAÑO'), ('Calz', 'CALZADOS'), ('Acc', 'ACCESORIOS')], default='Jeans', max_length=20, unique=True),
        ),
    ]
