# Generated by Django 3.2.2 on 2021-10-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0009_auto_20211021_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_id',
            field=models.PositiveIntegerField(default='', unique=True, verbose_name='codigo_art'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default='', max_length=20, verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talle',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talle',
            name='talle',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='talles'),
        ),
        migrations.AlterModelTable(
            name='talle',
            table='e_shop_talle',
        ),
    ]
