# Generated by Django 3.2.2 on 2022-01-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0009_remove_articulo_stock_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
