# Generated by Django 3.2.2 on 2021-10-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0010_auto_20211022_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='talle',
            new_name='talle_id',
        ),
    ]
