# Generated by Django 3.2.2 on 2022-01-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0010_color_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='picture',
        ),
        migrations.AlterField(
            model_name='color',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
    ]
