# Generated by Django 3.2.2 on 2021-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0011_rename_talle_articulo_talle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='picture',
            field=models.ImageField(default='', upload_to='picture/.', verbose_name='picture'),
        ),
    ]
