# Generated by Django 3.2.2 on 2022-01-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0011_auto_20220105_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
