# Generated by Django 3.2.2 on 2021-10-26 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_shop', '0012_alter_articulo_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('cart', models.BooleanField(default=False, verbose_name='carts')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished qty')),
                ('buied_qty', models.PositiveIntegerField(default=0, verbose_name='buied qty')),
                ('art_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='e_shop.articulo', verbose_name='Articulo')),
                ('user_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'e_shop_wish_list',
            },
        ),
    ]
