# Generated by Django 3.2.2 on 2022-01-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0013_articulo_stock_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='stock_qty',
        ),
    ]
