# Generated by Django 3.2.2 on 2022-02-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0014_remove_articulo_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_id',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='codigo_art'),
        ),
    ]
