# Generated by Django 3.2.2 on 2022-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0015_alter_articulo_art_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='codigo_art'),
        ),
    ]
