# Generated by Django 3.2.2 on 2022-02-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0016_alter_articulo_art_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='buied_qty',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_qty',
        ),
    ]
